<!-- author, publisher, copyright ARiS websitewerk - www.websitewerk.nl-->
function strstr(a,b){var c=0,c=(a+"").indexOf(b);return-1==c?!1:!0}function createCookie(a,b,c){if(c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="; expires="+d.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/"}function readCookie(a){var b=a+"=",c=document.cookie.split(";");if(strstr(document.cookie,a))for(a=0;a<c.length;a++){for(var d=c[a];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(b))return d.substring(b.length,d.length)}return null}
function eraseCookie(a){createCookie(a,"",-1)}function is_child_of(a,b){if(null!=b)for(;b.parentNode;)if((b=b.parentNode)==a)return!0;return null!=b?!1:!0}function fixOnMouseOut(a,b,c){var d=null;b.toElement?d=b.toElement:b.relatedTarget&&(d=b.relatedTarget);is_child_of(a,d)||a==d||eval(c)}
google.maps.LatLng.prototype.distanceFrom=function(a){var b=this.lat(),c=this.lng(),d=a.lat(),e=a.lng();a=(d-b)*Math.PI/180;c=(e-c)*Math.PI/180;b=Math.sin(a/2)*Math.sin(a/2)+Math.cos(b*Math.PI/180)*Math.cos(d*Math.PI/180)*Math.sin(c/2)*Math.sin(c/2);return 12742E3*Math.atan2(Math.sqrt(b),Math.sqrt(1-b))};function getValue(a){radios=document.getElementsByName(a);for(i=0;i<radios.length;i++)if(radios[i].checked)return radios[i].value}
function convertd2dm(a){""==a?myminutes=mydegrees="":(absdegrees=Math.abs(a),mydegrees=parseInt(absdegrees),remaining=absdegrees-1*mydegrees,myminutes=60*remaining,myminutes=Math.round(1E3*myminutes)/1E3,mydir=0>a?-1:1)}
function convertd2dms(a){if(""==a)myseconds=myminutes=mydegrees="";else{absdegrees=Math.abs(a);mydegrees=parseInt(absdegrees);remaining=absdegrees-1*mydegrees;var b=60*remaining;myminutes=parseInt(b);remaining=b-1*myminutes;myseconds=60*remaining;myseconds=Math.round(10*myseconds)/10;mydir=0>a?-1:1}}function clearTextInput(a,b){document.getElementById(a).value==b&&(document.getElementById(a).value="")}var textcount=0;
function displayText(a,b){"control"==a?(0<textcount&&KnipperUit(),textcount++,myid="ctltxt"+textcount,$("#topcontrol").css("visibility","visible"),$("#topcontrol").prepend($('<span id="'+myid+'">> '+b+"</span><br>")),Knipper()):document.getElementById(a).innerHTML=b}function displayClear(a){"control"!=a?document.getElementById(a).innerHTML="":0<textcount&&(myid="ctltxt"+textcount,KnipperUit())}var geocoder=new google.maps.Geocoder,myzindex=10;
function inczindex(a){myzindex++;document.getElementById(a).style.zIndex=myzindex}function closeMyframe(){document.getElementById("myframe").style.display="none"}function showAddress(a){addressalert=address=a;geocoder.geocode({address:address},function(a,c){c==google.maps.GeocoderStatus.OK?(latitude=a[0].geometry.location.lat(),longitude=a[0].geometry.location.lng(),showLoc(1)):(alert("Er is een probleem met de ingevoerde locatie."),document.getElementById("adres").value="")})}var knipperset=!1;
function doItOn(){knipperset&&(myid="ctltxt"+textcount,document.getElementById(myid).style.visibility="visible",document.getElementById(myid).style.backgroundColor="#C00",document.getElementById(myid).style.color="#FFF",setTimeout("doItOff(myid)",1E3))}function doItOff(){knipperset&&(myid="ctltxt"+textcount,document.getElementById(myid).style.backgroundColor="#E6F3F3",document.getElementById(myid).style.color="#C00",setTimeout("doItOn(myid)",1E3))}
function Knipper(){knipperset||(knipperset=!0,doItOn())}function KnipperUit(){myid="ctltxt"+textcount;document.getElementById(myid).style.backgroundColor="#E6F3F3";document.getElementById(myid).style.color="#000";knipperset=!1}function addslashes(a){return(a+"").replace(/[\\"']/g,"\\$&").replace(/\u0000/g,"\\0")};