var nullvalue=999.9,rawlatitude="",rawlongitude="",baseband=nullvalue,basezone=nullvalue,baselatitude=nullvalue,baselongitude=nullvalue,latlngflag="latitude",splittedtxt=[];
function postfix2prefix(a){tmplength=a.length;1<tmplength?(tmpchar=a.substring(tmplength-1,tmplength),tmpresult="N"==tmpchar||"E"==tmpchar||"W"==tmpchar||"S"==tmpchar?tmpchar+a.substring(0,tmplength-1):a):tmpresult=a;tmpresult=tmpresult.replace(/N /g,"N");tmpresult=tmpresult.replace(/E /g,"E");tmpresult=tmpresult.replace(/W /g,"W");tmpresult=tmpresult.replace(/S /g,"S");return tmpresult=tmpresult.trim()}
function preprocessRaw(a){tmpresult=a.replace(/'/g," ");tmpresult=tmpresult.replace(/`/g," ");tmpresult=tmpresult.replace(/\u2032/g," ");tmpresult=tmpresult.replace(/''/g," ");tmpresult=tmpresult.replace(/``/g," ");tmpresult=tmpresult.replace(/\u2032\u2032/g," ");tmpresult=tmpresult.replace(/"/g," ");tmpresult=tmpresult.replace(/\u2033/g," ");tmpresult=tmpresult.replace(/\u00b0/g," ");tmpresult=tmpresult.replace(/N /g,"N");tmpresult=tmpresult.replace(/E /g,"E");tmpresult=tmpresult.replace(/W /g,"W");
tmpresult=tmpresult.replace(/S /g,"S");tmpresult=tmpresult.replace(/ N/g,"N");tmpresult=tmpresult.replace(/ E/g,"E");tmpresult=tmpresult.replace(/ W/g,"W");tmpresult=tmpresult.replace(/ S/g,"S");tmpresult=tmpresult.replace(/  /g," ");tmpresult=tmpresult.replace(/  /g," ");return tmpresult=tmpresult.replace(/  /g," ")}
function preprocess(a){tmpresult=a.toUpperCase();tmpresult=tmpresult.replace(/   /g," ");tmpresult=tmpresult.replace(/  /g," ");tmpresult=tmpresult.replace(/  /g," ");return tmpresult=tmpresult.replace(/  /g," ")}function precheck(a){return""==a?"input empty":3<a.split(".").length?"max 2 dots expected":3<a.split(",").length?"max 2 comma's expected":"OK"}function nofoccurences(a,b){return b.split(a).length-1}
function nofprefixes(a){return nofoccurences("N",a)+nofoccurences("E",a)+nofoccurences("W",a)+nofoccurences("S",a)}function isNormalInteger(a){return/^\+?(0|[1-9]\d*)$/.test(a)}function lastcharisletter(a){inlastchar=a[a.length-1];return inlastchar.match(/[a-z]/i)?!0:!1}function maybezone(a){inlastchar=a[a.length-1];return lastcharisletter(a)?!0:isNormalInteger(a)?0<a&&60>=a?!0:!1:!1}function maybeeasting(a){return 166E3<=a&&836E3>=a?!0:!1}
function getLatLng(a){rawband=rawzone="";tmplength=0;precheckResult=precheck(a);processedtxt="";splittedtxt[0]="";splittedtxt[1]="";splittedtxt[2]="";splittedtxt[3]="";splittedtxt[4]="";splittedtxt[5]="";splittedtxt[6]="";splittedtxt[7]="";if("OK"==precheckResult)if(processedtxt=a,processedtxt=preprocess(processedtxt),processedtxt=processedtxt.trim(),""!=processedtxt)if(-1<processedtxt.search(","))tmplength=processedtxt.split(",").length,2==tmplength?(splittedtxt=processedtxt.split(","),rawlatitude=
splittedtxt[0],rawlongitude=splittedtxt[1]):3==tmplength?(splittedtxt=processedtxt.split(","),maybezone(splittedtxt[0].trim())&&maybeeasting(splittedtxt[1].trim())?(lastcharisletter(splittedtxt[0])?(rawzone=splittedtxt[0].trim().substring(0,splittedtxt[0].trim().length-1),rawband=splittedtxt[0].trim().substring(splittedtxt[0].trim().length-1,splittedtxt[0].trim().length)):(rawzone=splittedtxt[0].trim(),rawband="T"),rawlatitude=splittedtxt[1].trim(),rawlongitude=splittedtxt[2].trim()):precheckResult=
"unexpected input"):4==tmplength?(splittedtxt=processedtxt.split(","),rawzone=splittedtxt[0],lastcharisletter(splittedtxt[1])?(rawzone=splittedtxt[0],rawband=splittedtxt[1],rawlatitude=splittedtxt[2],rawlongitude=splittedtxt[3]):precheckResult="unexpected input"):precheckResult="unexpected input";else{tmplength=processedtxt.split(" ").length;if(5==tmplength||7==tmplength||9<=tmplength)return"inputs unbalanced";1==tmplength?(rawlatitude=processedtxt,rawlongitude=""):2==tmplength?(splittedtxt=processedtxt.split(" "),
1==nofprefixes(processedtxt)?(rawlatitude=splittedtxt[0]+" "+splittedtxt[1],rawlongitude=""):(rawlatitude=splittedtxt[0],rawlongitude=splittedtxt[1])):3==tmplength?(splittedtxt=processedtxt.split(" "),console.log(splittedtxt[1]),maybezone(splittedtxt[0])&&maybeeasting(splittedtxt[1])?(lastcharisletter(splittedtxt[0])?(rawzone=splittedtxt[0].substring(0,splittedtxt[0].length-1),rawband=splittedtxt[0].substring(splittedtxt[0].length-1,splittedtxt[0].length)):(rawzone=splittedtxt[0],rawband="T"),rawlatitude=
splittedtxt[1],rawlongitude=splittedtxt[2]):(rawlatitude=splittedtxt[0]+" "+splittedtxt[1]+" "+splittedtxt[2],rawlongitude="")):4==tmplength?(splittedtxt=processedtxt.split(" "),maybezone(splittedtxt[0])&&lastcharisletter(splittedtxt[1])?(rawzone=splittedtxt[0],rawband=splittedtxt[1],rawlatitude=splittedtxt[2],rawlongitude=splittedtxt[3]):1==nofprefixes(processedtxt)?(rawlatitude=splittedtxt[0]+" "+splittedtxt[1]+" "+splittedtxt[2]+" "+splittedtxt[3],rawlongitude=""):(rawlatitude=splittedtxt[0]+" "+
splittedtxt[1],rawlongitude=splittedtxt[2]+" "+splittedtxt[3])):6==tmplength?(splittedtxt=processedtxt.split(" "),rawlatitude=splittedtxt[0]+" "+splittedtxt[1]+" "+splittedtxt[2],rawlongitude=splittedtxt[3]+" "+splittedtxt[4]+" "+splittedtxt[5]):8==tmplength&&(splittedtxt=processedtxt.split(" "),rawlatitude=splittedtxt[0]+" "+splittedtxt[1]+" "+splittedtxt[2]+" "+splittedtxt[3],rawlongitude=splittedtxt[4]+" "+splittedtxt[5]+" "+splittedtxt[6]+" "+splittedtxt[7])}else precheckResult="invalid input";
return precheckResult}function negativeinput(a){return"S"==a.substring(0,1)||"-"==a.substring(0,1)||"_"==a.substring(0,1)?(latlngflag="latitude",!0):"W"==a.substring(0,1)?(latlngflag="longitude",!0):!1}function positiveinput(a){return"N"==a.substring(0,1)?(latlngflag="latitude",!0):"E"==a.substring(0,1)?(latlngflag="longitude",!0):!1}
function convertD2D(a){negativeinput(a)?(tmpresult=a.substring(1),tmpresult=-1*parseFloat(tmpresult)):positiveinput(a)?(tmpresult=a.substring(1),tmpresult=parseFloat(tmpresult)):tmpresult=parseFloat(a);return tmpresult}
function convertDM2D(a,b){if(60<=parseFloat(b))return alert("minutes >= 60"),nullvalue;negativeinput(a)?(tmpresult=a.substring(1),tmpresult=parseFloat(tmpresult)+parseFloat(b)/60,tmpresult*=-1):positiveinput(a)?(tmpresult=a.substring(1),tmpresult=parseFloat(tmpresult)+parseFloat(b)/60):tmpresult=parseFloat(a)+parseFloat(b)/60;return tmpresult}
function convertDMS2D(a,b,c){if(60<=parseFloat(b))return alert("minutes >= 60"),nullvalue;if(60<=parseFloat(c))return alert("seconds >= 60"),nullvalue;negativeinput(a)?(tmpresult=a.substring(1),tmpresult=parseFloat(tmpresult)+parseFloat(b)/60,tmpresult+=parseFloat(c)/3600,tmpresult*=-1):(positiveinput(a)?(tmpresult=a.substring(1),tmpresult=parseFloat(tmpresult)+parseFloat(b)/60):tmpresult=parseFloat(a)+parseFloat(b)/60,tmpresult+=parseFloat(c)/3600);return tmpresult}
function raw2base(a){baseresult=nullvalue;splittedtxt[0]="";splittedtxt[1]="";splittedtxt[2]="";splittedtxt=a.split(" ");""==a?baseresult=nullvalue:1==a.split(" ").length?baseresult=convertD2D(splittedtxt[0]):2==a.split(" ").length?baseresult=convertDM2D(splittedtxt[0],splittedtxt[1]):3==a.split(" ").length?baseresult=convertDMS2D(splittedtxt[0],splittedtxt[1],splittedtxt[2]):(alert("unexpected input"),baseresult=nullvalue);return baseresult}function decimal5(a){return parseFloat(a).toFixed(5)}
function decimal3(a){return parseFloat(a).toFixed(3)}function decimal1(a){return parseFloat(a).toFixed(1)}function d2xy(a,b){tmplat=parseFloat(a);tmplng=parseFloat(b);return 50.57<tmplat&&53.63>tmplat&&3.29<tmplng&&7.58>tmplng?(X=gps2X(tmplat,tmplng),Y=gps2Y(tmplat,tmplng),X.toFixed(0)+", "+Y.toFixed(0)):txt_rd_buiten_bereik}function d2d(a){return""+decimal5(a)}
function d2dm(a,b){tmpfloat=parseFloat(a);0>tmpfloat?(booleannegative=!0,tmpfloat*=-1):booleannegative=!1;mydegrees=Math.floor(decimal5(tmpfloat));myremaining=tmpfloat-mydegrees;myminutes=Math.abs(60*myremaining);tmpresult=booleannegative?"latitude"==b?"S ":"W ":"latitude"==b?"N ":"E ";return tmpresult=tmpresult+parseInt(mydegrees)+" "+decimal3(myminutes)}
function d2dms(a,b){tmpfloat=parseFloat(a);0>tmpfloat?(booleannegative=!0,tmpfloat*=-1):booleannegative=!1;mydegrees=Math.floor(decimal5(tmpfloat));myremaining=tmpfloat-mydegrees;myrawminutes=decimal3(60*myremaining);myminutes=Math.floor(myrawminutes);myremaining=myrawminutes-myminutes;myseconds=Math.abs(60*myremaining);tmpresult=booleannegative?"latitude"==b?"S ":"W ":"latitude"==b?"N ":"E ";return tmpresult=tmpresult+parseInt(mydegrees)+" "+parseInt(myminutes)+" "+decimal1(myseconds)}
function flexibleinput2latlng(a){tmpresult=getLatLng(a);"OK"==tmpresult?""==rawzone?(rawlatitude=preprocessRaw(rawlatitude),rawlongitude=preprocessRaw(rawlongitude),rawlatitude=postfix2prefix(rawlatitude),rawlongitude=postfix2prefix(rawlongitude),baseband=basezone=nullvalue,baselatitude=raw2base(rawlatitude),baselongitude=raw2base(rawlongitude)):(basezone=rawzone,baseband=rawband,baselatitude=rawlongitude,baselongitude=rawlatitude):(alert(tmpresult),baselongitude=baselatitude=baseband=basezone=nullvalue)}
;